import { Anomaly, StoreMeta, StoreFilter, Severity, Category } from './types';

// TODO: ganti STORES.confidence/coverage dengan formula asli setelah
// Reconciliation Engine dan definisi Audit Confidence dibangun. Angka di
// bawah masih placeholder manual, bukan hasil kalkulasi.
export const STORES: StoreMeta[] = [
  { id: 'a', label: 'Toko A', confidence: 91, coverage: 90, freshnessDays: 1, freshnessLabel: '1 hari lalu', sources: { sales: true, purchase: true, waste: true, opname: true } },
  { id: 'b', label: 'Toko B', confidence: 87, coverage: 85, freshnessDays: 2, freshnessLabel: '2 hari lalu', sources: { sales: true, purchase: true, waste: true, opname: true } },
  { id: 'c', label: 'Toko C', confidence: 68, coverage: 60, freshnessDays: 3, freshnessLabel: '3 hari lalu', sources: { sales: true, purchase: true, waste: false, opname: true } },
];

export const ANOMALIES: Anomaly[] = [
  { id:'TG-A-231', store:'a', storeLabel:'Toko A', date:'04 Sep 2026', title:'Payment mismatch', category:'payment', type:'reconciliation', severity:'critical', status:'Belum diperiksa', expected:'Rp 12.450.000', actual:'Rp 10.000.000', variance:'Rp 2.450.000', sourceData:'184 transaksi sales tercatat, dibandingkan payment gateway settlement report periode 01–04 Sep 2026', calculation:'Total sales tercatat (Rp12.450.000) dibandingkan total settlement payment gateway (Rp10.000.000)', ruleTriggered:'Variance melebihi threshold toleransi rekonsiliasi payment', recountLabel:null, evidenceDetail:['Store: Toko A','Periode: 01–04 Sep 2026','Sumber: Sales log, Payment gateway settlement'] },
  { id:'TG-A-118', store:'a', storeLabel:'Toko A', date:'03 Sep 2026', title:'Stock variance — Gula 1kg', category:'stock', type:'reconciliation', severity:'high', status:'Belum diperiksa', expected:'120 kg', actual:'108 kg', variance:'12 kg', sourceData:'Purchase order, sales log, dan stock opname fisik 03 Sep 2026', calculation:'Stok awal + pembelian − penjualan = expected 120 kg; dibandingkan hasil stock opname fisik 108 kg', ruleTriggered:'Variance stok melebihi threshold toleransi rekonsiliasi stock', recountLabel:'Perlu hitung fisik stok ulang', evidenceDetail:['Store: Toko A','Tanggal opname: 03 Sep 2026','Sumber: Purchase order, Sales log, Stock opname'] },
  { id:'TG-A-247', store:'a', storeLabel:'Toko A', date:'02 Sep 2026', title:'Refund spike — shift malam', category:'pattern', type:'behavioral', severity:'high', status:'Belum diperiksa', sourceData:'6 refund tercatat pada shift malam, 02 Sep 2026', detectionRule:'Refund per shift > 3x rata-rata 30 hari terakhir (baseline 1–2 refund/shift)', observedPattern:'6 refund dalam 1 shift, seluruhnya dalam rentang 2 jam', reasonFlagged:'Frekuensi jauh di atas baseline dan terkonsentrasi dalam waktu singkat — evidence transaksi tersedia untuk direview manual', evidenceDetail:['Store: Toko A','Shift: malam, 02 Sep 2026','Sumber: Sales log (refund transactions)'] },
  { id:'TG-A-090', store:'a', storeLabel:'Toko A', date:'01 Sep 2026', title:'Void count abnormal', category:'pattern', type:'behavioral', severity:'medium', status:'Belum diperiksa', sourceData:'5 void tercatat pada 1 shift, 01 Sep 2026', detectionRule:'Void per shift melebihi baseline historis (1–2 void/shift)', observedPattern:'5 void dalam 1 shift, di atas baseline 1–2 void/shift', reasonFlagged:'Frekuensi void di atas baseline, evidence transaksi tersedia untuk direview manual', evidenceDetail:['Store: Toko A','Tanggal: 01 Sep 2026','Sumber: Sales log (void transactions)'] },
  { id:'TG-A-142', store:'a', storeLabel:'Toko A', date:'31 Aug 2026', title:'Cash variance — shift pagi', category:'cash', type:'reconciliation', severity:'medium', status:'Belum diperiksa', expected:'Rp 1.200.000', actual:'Rp 1.115.000', variance:'Rp 85.000', sourceData:'Kas closing shift pagi 31 Aug 2026: kas awal, transaksi cash, pengeluaran tercatat', calculation:'Kas awal + kas masuk − kas keluar = expected Rp1.200.000; dibandingkan hasil hitung fisik saat closing Rp1.115.000', ruleTriggered:'Variance kas melebihi threshold toleransi rekonsiliasi cash', recountLabel:'Perlu hitung ulang kas', evidenceDetail:['Store: Toko A','Waktu: closing shift pagi, 31 Aug 2026','Sumber: Cash log, Payment log'] },
  { id:'TG-A-076', store:'a', storeLabel:'Toko A', date:'30 Aug 2026', title:'Discount pattern unusual', category:'pattern', type:'behavioral', severity:'low', status:'Belum diperiksa', sourceData:'Rata-rata discount 8% di atas baseline, 30 Aug 2026', detectionRule:'Discount rate melebihi baseline historis', observedPattern:'8% di atas rata-rata discount 30 hari terakhir', reasonFlagged:'Pola discount di luar kebiasaan, butuh review manual', evidenceDetail:['Store: Toko A','Tanggal: 30 Aug 2026','Sumber: Sales log'] },
  { id:'TG-A-061', store:'a', storeLabel:'Toko A', date:'29 Aug 2026', title:'Transaction time outlier', category:'pattern', type:'behavioral', severity:'low', status:'Belum diperiksa', sourceData:'2 transaksi tercatat di luar jam operasional, 29 Aug 2026', detectionRule:'Transaksi di luar jam operasional normal toko', observedPattern:'2 transaksi di luar jam operasional pada tanggal tersebut', reasonFlagged:'Waktu transaksi di luar pola normal toko, butuh review manual', evidenceDetail:['Store: Toko A','Tanggal: 29 Aug 2026','Sumber: Sales log'] },
  { id:'TG-B-201', store:'b', storeLabel:'Toko B', date:'04 Sep 2026', title:'Stock variance — Minyak Goreng', category:'stock', type:'reconciliation', severity:'high', status:'Belum diperiksa', expected:'60 liter', actual:'51 liter', variance:'9 liter', sourceData:'Purchase order, sales log, dan stock opname fisik 04 Sep 2026', calculation:'Stok awal + pembelian − penjualan = expected 60 liter; dibandingkan hasil stock opname fisik 51 liter', ruleTriggered:'Variance stok melebihi threshold toleransi rekonsiliasi stock', recountLabel:'Perlu hitung fisik stok ulang', evidenceDetail:['Store: Toko B','Tanggal opname: 04 Sep 2026','Sumber: Purchase order, Sales log, Stock opname'] },
  { id:'TG-B-188', store:'b', storeLabel:'Toko B', date:'03 Sep 2026', title:'Payment gateway mismatch', category:'payment', type:'reconciliation', severity:'high', status:'Belum diperiksa', expected:'Rp 4.100.000', actual:'Rp 3.780.000', variance:'Rp 320.000', sourceData:'Sales log dibandingkan payment gateway settlement report, 03 Sep 2026', calculation:'Total sales tercatat (Rp4.100.000) dibandingkan total settlement payment gateway (Rp3.780.000)', ruleTriggered:'Variance melebihi threshold toleransi rekonsiliasi payment', recountLabel:null, evidenceDetail:['Store: Toko B','Periode: 03 Sep 2026','Sumber: Sales log, Payment gateway settlement'] },
  { id:'TG-B-102', store:'b', storeLabel:'Toko B', date:'02 Sep 2026', title:'Adjustment tanpa approval', category:'pattern', type:'behavioral', severity:'medium', status:'Belum diperiksa', sourceData:'3 adjustment stok tercatat tanpa approval, 02 Sep 2026', detectionRule:'Adjustment stok tanpa approval tercatat di sistem', observedPattern:'3 adjustment dalam 1 hari, tidak ada approval terkait', reasonFlagged:'Adjustment dilakukan di luar prosedur approval standar', evidenceDetail:['Store: Toko B','Tanggal: 02 Sep 2026','Sumber: Stock log'] },
  { id:'TG-B-095', store:'b', storeLabel:'Toko B', date:'01 Sep 2026', title:'Void count abnormal', category:'pattern', type:'behavioral', severity:'medium', status:'Belum diperiksa', sourceData:'3 void tercatat pada 1 shift, 01 Sep 2026', detectionRule:'Void per shift melebihi baseline historis', observedPattern:'3 void dalam 1 shift, di atas baseline', reasonFlagged:'Frekuensi void di atas baseline, evidence transaksi tersedia untuk direview manual', evidenceDetail:['Store: Toko B','Tanggal: 01 Sep 2026','Sumber: Sales log (void transactions)'] },
  { id:'TG-B-081', store:'b', storeLabel:'Toko B', date:'31 Aug 2026', title:'Cash variance — shift sore', category:'cash', type:'reconciliation', severity:'medium', status:'Belum diperiksa', expected:'Rp 900.000', actual:'Rp 860.000', variance:'Rp 40.000', sourceData:'Kas closing shift sore 31 Aug 2026: kas awal, transaksi cash, pengeluaran tercatat', calculation:'Kas awal + kas masuk − kas keluar = expected Rp900.000; dibandingkan hasil hitung fisik saat closing Rp860.000', ruleTriggered:'Variance kas melebihi threshold toleransi rekonsiliasi cash', recountLabel:'Perlu hitung ulang kas', evidenceDetail:['Store: Toko B','Waktu: closing shift sore, 31 Aug 2026','Sumber: Cash log, Payment log'] },
  { id:'TG-B-070', store:'b', storeLabel:'Toko B', date:'30 Aug 2026', title:'Discount pattern unusual', category:'pattern', type:'behavioral', severity:'low', status:'Belum diperiksa', sourceData:'Rata-rata discount 5% di atas baseline, 30 Aug 2026', detectionRule:'Discount rate melebihi baseline historis', observedPattern:'5% di atas rata-rata discount 30 hari terakhir', reasonFlagged:'Pola discount di luar kebiasaan, butuh review manual', evidenceDetail:['Store: Toko B','Tanggal: 30 Aug 2026','Sumber: Sales log'] },
  { id:'TG-C-142', store:'c', storeLabel:'Toko C', date:'31 Aug 2026', title:'Cash variance', category:'cash', type:'reconciliation', severity:'high', status:'Belum diperiksa', expected:'Rp 3.550.000', actual:'Rp 3.400.000', variance:'Rp 150.000', sourceData:'Kas closing shift 31 Aug 2026: kas awal, transaksi cash, pengeluaran tercatat', calculation:'Kas awal + kas masuk − kas keluar = expected Rp3.550.000; dibandingkan hasil hitung fisik saat closing Rp3.400.000', ruleTriggered:'Variance kas melebihi threshold toleransi rekonsiliasi cash', recountLabel:'Perlu hitung ulang kas', evidenceDetail:['Store: Toko C','Waktu: closing shift, 31 Aug 2026','Sumber: Cash log, Payment log'] },
  { id:'TG-C-118', store:'c', storeLabel:'Toko C', date:'03 Sep 2026', title:'Stock variance — Beras 5kg', category:'stock', type:'reconciliation', severity:'critical', status:'Belum diperiksa', expected:'200 kg', actual:'160 kg', variance:'40 kg', sourceData:'Purchase order, sales log, dan stock opname fisik 03 Sep 2026', calculation:'Stok awal + pembelian − penjualan = expected 200 kg; dibandingkan hasil stock opname fisik 160 kg', ruleTriggered:'Variance stok melebihi threshold toleransi rekonsiliasi stock', recountLabel:'Perlu hitung fisik stok ulang', evidenceDetail:['Store: Toko C','Tanggal opname: 03 Sep 2026','Sumber: Purchase order, Sales log, Stock opname'] },
  { id:'TG-C-231', store:'c', storeLabel:'Toko C', date:'04 Sep 2026', title:'Payment mismatch', category:'payment', type:'reconciliation', severity:'critical', status:'Belum diperiksa', expected:'Rp 9.200.000', actual:'Rp 7.400.000', variance:'Rp 1.800.000', sourceData:'Sales log dibandingkan payment gateway settlement report, 04 Sep 2026', calculation:'Total sales tercatat (Rp9.200.000) dibandingkan total settlement payment gateway (Rp7.400.000)', ruleTriggered:'Variance melebihi threshold toleransi rekonsiliasi payment', recountLabel:null, evidenceDetail:['Store: Toko C','Periode: 04 Sep 2026','Sumber: Sales log, Payment gateway settlement'] },
  { id:'TG-C-247', store:'c', storeLabel:'Toko C', date:'02 Sep 2026', title:'Refund spike', category:'pattern', type:'behavioral', severity:'high', status:'Belum diperiksa', sourceData:'Refund 3x rata-rata baseline, 02 Sep 2026', detectionRule:'Refund per shift > 3x rata-rata 30 hari terakhir', observedPattern:'Refund pada shift ini 3x lipat baseline', reasonFlagged:'Frekuensi jauh di atas baseline — evidence transaksi tersedia untuk direview manual', evidenceDetail:['Store: Toko C','Tanggal: 02 Sep 2026','Sumber: Sales log (refund transactions)'] },
  { id:'TG-C-090', store:'c', storeLabel:'Toko C', date:'01 Sep 2026', title:'Void count abnormal', category:'pattern', type:'behavioral', severity:'high', status:'Belum diperiksa', sourceData:'6 void tercatat pada 1 shift, 01 Sep 2026', detectionRule:'Void per shift melebihi baseline historis', observedPattern:'6 void dalam 1 shift, jauh di atas baseline', reasonFlagged:'Frekuensi void jauh di atas baseline, evidence transaksi tersedia untuk direview manual', evidenceDetail:['Store: Toko C','Tanggal: 01 Sep 2026','Sumber: Sales log (void transactions)'] },
  { id:'TG-C-102', store:'c', storeLabel:'Toko C', date:'30 Aug 2026', title:'Adjustment tanpa approval', category:'pattern', type:'behavioral', severity:'medium', status:'Belum diperiksa', sourceData:'2 adjustment stok tercatat tanpa approval, 30 Aug 2026', detectionRule:'Adjustment stok tanpa approval tercatat di sistem', observedPattern:'2 adjustment dalam 1 hari, tidak ada approval terkait', reasonFlagged:'Adjustment dilakukan di luar prosedur approval standar', evidenceDetail:['Store: Toko C','Tanggal: 30 Aug 2026','Sumber: Stock log'] },
  { id:'TG-C-291', store:'c', storeLabel:'Toko C', date:'04 Sep 2026', title:'Stock shortfall — Susu (cause unconfirmed)', category:'stock', type:'insufficient', severity:null, tabSeverity:'low', status:'Insufficient data', gapNote:'observed gap: 4 liter (belum dikonfirmasi)', sourceAvail:'Sales tercatat 52 liter, Purchase tercatat 60 liter (periode 01–04 Sep 2026)', calcAttempt:'Purchase − Sales = 8 liter; stok fisik tersisa 4 liter → gap 4 liter belum terjelaskan', missingSource:'Waste — unavailable. Untuk kategori barang mudah rusak seperti susu, source ini material untuk memastikan penyebab gap.', explainWhy:'TokoGuard menemukan gap yang belum terjelaskan pada pergerakan stok Susu di Toko C, namun Waste record untuk toko ini belum tersedia.', ruleTriggered:'Gap terdeteksi dari selisih purchase-sales vs stok fisik, tapi confidence penuh butuh source waste yang belum ada', recountLabel:'Perlu hitung fisik stok ulang', evidenceDetail:['Store: Toko C','Periode: 01–04 Sep 2026','Sumber tersedia: Sales log, Purchase log','Sumber hilang: Waste log'] },
];

export function getAnomaliesForStore(store: StoreFilter): Anomaly[] {
  if (store === 'all') return ANOMALIES;
  return ANOMALIES.filter(a => a.store === store);
}

export function getRiskCounts(store: StoreFilter) {
  const list = getAnomaliesForStore(store);
  const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  let lowInsufficient = false;
  list.forEach(a => {
    if (a.severity === null) { lowInsufficient = true; return; }
    counts[a.severity]++;
  });
  return { counts, lowInsufficient };
}

export function getReconciliationCounts(store: StoreFilter) {
  const list = getAnomaliesForStore(store).filter(a => a.type === 'reconciliation');
  const cats: Category[] = ['payment', 'cash', 'stock'];
  return cats.map(cat => ({ category: cat, count: list.filter(a => a.category === cat).length }));
}

export function getStoreMeta(store: StoreFilter) {
  if (store !== 'all') {
    const s = STORES.find(s => s.id === store)!;
    return { confidence: s.confidence, coverage: s.coverage, freshnessLabel: s.freshnessLabel, sources: s.sources };
  }
  const confidence = Math.min(...STORES.map(s => s.confidence));
  const coverage = Math.min(...STORES.map(s => s.coverage));
  const worst = STORES.reduce((a, b) => (a.freshnessDays > b.freshnessDays ? a : b));
  const sources = {
    sales: STORES.every(s => s.sources.sales),
    purchase: STORES.every(s => s.sources.purchase),
    waste: STORES.every(s => s.sources.waste),
    opname: STORES.every(s => s.sources.opname),
  };
  return { confidence, coverage, freshnessLabel: `${worst.freshnessDays} hari lalu (kondisi terburuk antar toko)`, sources };
}

export function getAnomaliesForTab(store: StoreFilter, tab: 'all' | Severity): Anomaly[] {
  const list = getAnomaliesForStore(store);
  if (tab === 'all') return list;
  return list.filter(a => a.severity === tab || (a.type === 'insufficient' && a.tabSeverity === tab));
}
